#pragma once
////////////////////////////////////////////////////////////////////////////////
namespace agarai
{
  enum SensorType {
    LOCATION_X,
    LOCATION_Y,
    MASS,
    BIGGEST_NEIGHBOR_NE_MASS,
    BIGGEST_NEIGHBOR_NE_DISTANCE,
    BIGGEST_NEIGHBOR_NW_MASS,
    BIGGEST_NEIGHBOR_NW_DISTANCE,
    BIGGEST_NEIGHBOR_SW_MASS,
    BIGGEST_NEIGHBOR_SW_DISTANCE,
    BIGGEST_NEIGHBOR_SE_MASS,
    BIGGEST_NEIGHBOR_SE_DISTANCE,
    SMALLEST_NEIGHBOR_NE_MASS,
    SMALLEST_NEIGHBOR_NE_DISTANCE,
    SMALLEST_NEIGHBOR_NW_MASS,
    SMALLEST_NEIGHBOR_NW_DISTANCE,
    SMALLEST_NEIGHBOR_SW_MASS,
    SMALLEST_NEIGHBOR_SW_DISTANCE,
    SMALLEST_NEIGHBOR_SE_MASS,
    SMALLEST_NEIGHBOR_SE_DISTANCE,
    AVERAGE_NEIGHBOR_NE_MASS,
    AVERAGE_NEIGHBOR_NE_DISTANCE,
    AVERAGE_NEIGHBOR_NW_MASS,
    AVERAGE_NEIGHBOR_NW_DISTANCE,
    AVERAGE_NEIGHBOR_SW_MASS,
    AVERAGE_NEIGHBOR_SW_DISTANCE,
    AVERAGE_NEIGHBOR_SE_MASS,
    AVERAGE_NEIGHBOR_SE_DISTANCE,
    FOOD_DENSITY_NE,
    FOOD_DENSITY_NW,
    FOOD_DENSITY_SW,
    FOOD_DENSITY_SE,
    NUM_SENSES,
  };

  class Sensor {
    public:
      virtual float get(SensorType type) const = 0;
  };
}
